name: Run Qt Application

on:
  push:
    branches: [ main ]

jobs:
  run_qt_app:
    name: Run Qt App on Local Runner
    runs-on: self-hosted
    steps:

      - name: Lancer l'application Qt
        run: |
          echo "=== Lancement de l'application Qt ==="
          cd /home/farah/build-QT_APP_QML-Desktop-Debug
          ./MyCarApp
