name: Run Qt Application

on:
  push:
    branches: [ main ]


jobs:
  run_qt_app:
    name: Run Qt App on Local Runner
    runs-on: self-hosted
    steps:
      - name: Autoriser l'accès à X11
        run: |
          xhost +SI:localuser:$(whoami)

      - name: Lancer l'application Qt
        env:
          DISPLAY: ":0"
        run: |
          echo "=== Lancement de l'application Qt ==="
          nohup /home/farah/build-QT_APP_QML-Desktop-Debug/MyCarApp > &
          echo "=== Application Qt lancée. Logs dans $LOG_PATH ==="
